# Various utilities.

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "http_server",
    srcs = ["http_server.cc"],
    hdrs = ["http_server.h"],
    deps = [
        "@com_google_absl//absl/strings",
        "@com_google_absl//absl/log",
        "@com_google_absl//absl/log:check",
    ],
)
